# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('foodtype', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('foodstatus', models.BooleanField(default=False)),
                ('paidstatus', models.BooleanField(default=False)),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmightyrestaurant.MenuItem')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('workertype', models.CharField(choices=[('owner', 'Owner'), ('cook', 'Cook'), ('server', 'Server')], max_length=10)),
                ('hirement', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmightyrestaurant.Worker'),
        ),
    ]
