# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmightyrestaurant', '0003_worker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='workertype',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('cook', 'Cook'), ('server', 'Server')], max_length=10, null=True),
        ),
    ]
