# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmightyrestaurant', '0008_remove_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revisions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='revisionstatus',
            field=models.BooleanField(default=False),
        ),
    ]
