# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmightyrestaurant', '0009_auto_20160709_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='revisions',
            new_name='revision',
        ),
    ]
