# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appmightyrestaurant', '0010_auto_20160709_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderdate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 9, 16, 7, 21, 338867, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
