# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmightyrestaurant', '0011_order_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='paidstatus',
            field=models.BooleanField(default=False),
        ),
    ]
